version: "3.8"

services:
  postgres:
    image: pgvector/pgvector:pg17 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  identity-api:
    image: syedafatima14/eshop-identity-api:latest
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5105:8080"
    environment:
      ConnectionStrings__identitydb: "Host=postgres;Database=identitydb;Username=postgres;Password=postgres"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 15
      start_period: 15s


  catalog-api:
    image: syedafatima14/eshop-catalog-api:latest
    depends_on:
      - postgres
    ports:
      - "5101:8080"
    environment:
      ConnectionStrings__catalogdb: "Host=postgres;Database=catalogdb;Username=postgres;Password=postgres"

  basket-api:
    image: syedafatima14/eshop-basket-api:latest
    depends_on:
      - redis
    ports:
      - "5102:8080"
    environment:
      ConnectionStrings__basketdb: "redis:6379"

  ordering-api:
    image: syedafatima14/eshop-ordering-api:latest
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "5103:8080"
    environment:
      ConnectionStrings__orderingdb: "Host=postgres;Database=orderingdb;Username=postgres;Password=postgres"

  webapp:
    image: syedafatima14/eshop-webapp:latest
    depends_on:
      - catalog-api
      - basket-api
      - ordering-api
      - identity-api
    ports:
      - "8090:8080"
    environment:
      IdentityUrl: "http://identity-api:8080"
      CallBackUrl: "http://104.211.17.5:8090"

volumes:
  pgdata:
